baseURL: 'https://andyksaw.github.io'
languageCode: en-us
title: andysaw
theme: PaperMod

params:
  env: production
  assets:
    disableHLJS: true
  homeInfoParams:
    Content: "The ramblings of a Tokyo-based, ramen-powered, software engineer"
  socialIcons:
    - name: "linkedin"
      url: "https://linkedin.com/in/andy-saw/"
    - name: "github"
      url: "https://github.com/andyksaw"
  ShowReadingTime: true
  # ShowToc: false
  ShowCodeCopyButtons: true
  ShowPostNavLinks: false
  TocSide: 'left'

markup:
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    # noClasses: false
    style: monokai

menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: search
      name: search
      url: /search/
      weight: 30
    - identifier: archive
      name: archive
      url: /archives/
      weight: 40

outputs:
    home:
    - HTML
    - RSS
    - JSON # is necessary